-- Expand TriageIntent so fewer emails land in OTHER
ALTER TYPE "TriageIntent" ADD VALUE IF NOT EXISTS 'ORDER_ISSUE';
ALTER TYPE "TriageIntent" ADD VALUE IF NOT EXISTS 'RETURN_REFUND';
ALTER TYPE "TriageIntent" ADD VALUE IF NOT EXISTS 'PRODUCT_QUESTION';
ALTER TYPE "TriageIntent" ADD VALUE IF NOT EXISTS 'POSITIVE_FEEDBACK';
