/**
 * First-name based gender inference for insights breakdowns.
 *
 * Built-in list of common US first names (the store is US-centric), no
 * external API. Names that are genuinely unisex in the US (Taylor, Jordan,
 * Casey...) are intentionally absent so they land in "unknown" rather than
 * polluting the split. This is an aggregate-statistics heuristic only - it is
 * never used to address an individual customer.
 */

export type InferredGender = 'female' | 'male' | 'unknown';

const FEMALE = new Set([
  'mary', 'patricia', 'jennifer', 'linda', 'elizabeth', 'barbara', 'susan',
  'jessica', 'sarah', 'karen', 'lisa', 'nancy', 'betty', 'sandra', 'margaret',
  'ashley', 'kimberly', 'emily', 'donna', 'michelle', 'carol', 'amanda',
  'melissa', 'deborah', 'stephanie', 'rebecca', 'sharon', 'laura', 'cynthia',
  'dorothy', 'amy', 'kathleen', 'angela', 'shirley', 'emma', 'brenda',
  'pamela', 'nicole', 'anna', 'samantha', 'katherine', 'christine', 'debra',
  'rachel', 'carolyn', 'janet', 'maria', 'olivia', 'heather', 'helen',
  'catherine', 'diane', 'julie', 'victoria', 'joyce', 'lauren', 'kelly',
  'christina', 'ruth', 'joan', 'virginia', 'judith', 'evelyn', 'hannah',
  'andrea', 'megan', 'cheryl', 'jacqueline', 'madison', 'teresa', 'abigail',
  'sophia', 'martha', 'sara', 'gloria', 'janice', 'kathryn', 'ann', 'isabella',
  'judy', 'charlotte', 'julia', 'grace', 'amber', 'alice', 'jean', 'denise',
  'frances', 'danielle', 'marilyn', 'natalie', 'beverly', 'diana', 'brittany',
  'theresa', 'kayla', 'alexis', 'doris', 'lori', 'tiffany', 'rose',
  'cindy', 'kathy', 'tammy', 'wanda', 'bonnie', 'peggy', 'cathy', 'connie',
  'tracy', 'wendy', 'becky', 'vicki', 'vickie', 'sherry', 'sheri', 'rhonda',
  'darlene', 'maureen', 'colleen', 'eileen', 'lorraine', 'charlene', 'paula',
  'tina', 'gail', 'sally', 'sue', 'suzanne', 'ellen', 'elaine', 'marie',
  'annette', 'jeanette', 'yvonne', 'gina', 'kristen', 'kristin', 'kristina',
  'krista', 'kristi', 'kristy', 'christy', 'misty', 'mindy', 'monica',
  'melanie', 'melinda', 'belinda', 'miranda', 'veronica', 'valerie', 'vanessa',
  'erica', 'erika', 'erin', 'april', 'autumn', 'summer', 'dawn', 'faith',
  'hope', 'joy', 'crystal', 'jade', 'ruby', 'pearl', 'daisy', 'lily', 'violet',
  'iris', 'holly', 'heidi', 'ingrid', 'greta', 'sonja', 'sonya', 'tanya',
  'tonya', 'latoya', 'keisha', 'aisha', 'maya', 'mia', 'ava', 'ella', 'chloe',
  'zoe', 'zoey', 'nora', 'lucy', 'stella', 'hazel', 'aurora', 'savannah',
  'audrey', 'brooklyn', 'claire', 'skylar', 'lucia', 'paisley', 'everly',
  'anya', 'leah', 'aubrey', 'willow', 'addison', 'lillian', 'layla', 'naomi',
  'eleanor', 'gabriella', 'gabrielle', 'serenity', 'scarlett', 'penelope',
  'aria', 'arianna', 'adriana', 'alyssa', 'alicia', 'alison', 'allison',
  'alexandra', 'alexandria', 'cassandra', 'cassidy', 'chelsea', 'courtney',
  'desiree', 'destiny', 'gabriela', 'isabel', 'isabelle', 'jasmine', 'jenna',
  'jillian', 'jocelyn', 'kaitlyn', 'caitlin', 'katelyn', 'karla', 'kara',
  'kiara', 'kylie', 'kendra', 'kenzie', 'mackenzie', 'makayla', 'mikayla',
  'marisa', 'marissa', 'meredith', 'molly', 'paige', 'phoebe', 'priscilla',
  'rebekah', 'sabrina', 'sierra', 'tara', 'tessa', 'trisha', 'patti', 'patty',
  'penny', 'pam', 'deb', 'debbie', 'liz', 'lizzie', 'beth', 'bethany',
  'betsy', 'meg', 'maggie', 'midge', 'jan', 'jane', 'janie', 'jeanne',
  'jeannie', 'joanne', 'joanna', 'johanna', 'jodi', 'jody', 'jill', 'gwen',
  'gwendolyn', 'fay', 'faye', 'flora', 'florence', 'edith', 'edna', 'elsie',
  'esther', 'ethel', 'eva', 'eve', 'fern', 'gladys', 'harriet', 'hattie',
  'irene', 'irma', 'juanita', 'lillie', 'lois', 'lucille', 'mabel', 'mildred',
  'minnie', 'myrtle', 'norma', 'opal', 'phyllis', 'rosemary', 'sylvia',
  'thelma', 'vera', 'vivian', 'wilma', 'bertha', 'agnes', 'beatrice',
  'bernice', 'carla', 'carmen', 'carrie', 'cara', 'celeste', 'celia', 'clara',
  'claudia', 'corinne', 'dana', 'daniela', 'davina', 'deanna', 'dolores',
  'donna-marie', 'dora', 'eliza', 'elena', 'elisa', 'elise', 'eloise', 'gemma',
  'georgia', 'geraldine', 'gillian', 'gloria-jean', 'henrietta', 'jacquelyn',
  'janelle', 'janine', 'jeanine', 'josephine', 'josie', 'karina', 'katie',
  'kate', 'katy', 'kerri', 'kerry-ann', 'kim', 'lana', 'lara', 'laurie',
  'leann', 'leanne', 'lena', 'leslie-ann', 'lila', 'lilly', 'lindsay',
  'lindsey', 'lorena', 'lorie', 'lydia', 'lynn', 'lynne', 'lynda', 'madeline',
  'madeleine', 'mandy', 'marcia', 'marsha', 'margie', 'marge', 'marguerite',
  'marian', 'marianne', 'marlene', 'maryann', 'maryanne', 'mavis', 'maxine',
  'mercedes', 'michele', 'nadia', 'nadine', 'nanette', 'natasha', 'nellie',
  'nina', 'noelle', 'nan', 'olga', 'paulette', 'pauline', 'petra', 'polly',
  'ramona', 'regina', 'renee', 'rita', 'roberta', 'robyn', 'rosa', 'rosalie',
  'roseann', 'roxanne', 'sadie', 'selena', 'serena', 'sheila', 'shelley',
  'shelly', 'sherri', 'sherrie', 'sheryl', 'simone', 'sondra', 'sophie',
  'stacey', 'staci', 'stacie', 'susanna', 'susannah', 'susie', 'tabitha',
  'tamara', 'tami', 'terri', 'terrie', 'tia', 'tracey', 'traci', 'tricia',
  'trina', 'trudy', 'ursula', 'velma', 'verna', 'vicky', 'viola', 'wendi',
  'winifred', 'yolanda', 'yvette', 'zelda', 'gretchen', 'ginger', 'candace',
  'candice', 'candy', 'bridget', 'brigitte', 'bobbie', 'billie-jean',
  'antoinette', 'annmarie', 'annie', 'anita', 'angie', 'angelina', 'angelica',
  'amelia', 'allie', 'adrienne', 'adele', 'felicia', 'latasha', 'tasha',
  'shanna', 'shauna', 'shawna', 'sharlene', 'rochelle', 'raquel', 'portia',
  'noreen', 'nikki', 'mona', 'moira', 'mimi', 'millicent', 'mable', 'luann',
  'lottie', 'liza', 'lisbeth', 'leticia', 'letitia', 'leona', 'laverne',
  'lavonne', 'kitty', 'kira', 'keri', 'kelli', 'kellie', 'kayleigh', 'kaylee',
  'karol', 'kari', 'june', 'julianne', 'juliana', 'jolene', 'joann', 'jewel',
  'jessie-mae', 'jeri', 'jenifer', 'janis', 'janna', 'jana', 'ilene', 'imogene',
  'geri', 'georgina', 'francine', 'flossie', 'estelle', 'ernestine', 'erma',
  'emilia', 'elvira', 'elnora', 'effie', 'dottie', 'dorthy', 'dorene',
  'donnamarie', 'dixie', 'dinah', 'dianna', 'dianne', 'della', 'delores',
  'delia', 'deidre', 'deirdre', 'darla', 'cyndi', 'cristina', 'corrine',
  'cora', 'consuelo', 'clarice', 'claudette', 'christa', 'cherie', 'cecilia',
  'cecile', 'cathleen', 'caryn', 'camille', 'callie', 'brianna', 'breanna',
  'blanche', 'birdie', 'bianca', 'bess', 'bessie', 'bernadette', 'belle',
  'becca', 'beatriz', 'barb', 'aretha', 'ariel', 'arlene', 'athena', 'audra',
]);

const MALE = new Set([
  'james', 'robert', 'john', 'michael', 'david', 'william', 'richard',
  'joseph', 'thomas', 'charles', 'christopher', 'daniel', 'matthew', 'anthony',
  'mark', 'donald', 'steven', 'paul', 'andrew', 'joshua', 'kenneth', 'kevin',
  'brian', 'george', 'timothy', 'ronald', 'edward', 'jason', 'jeffrey', 'ryan',
  'jacob', 'gary', 'nicholas', 'eric', 'jonathan', 'stephen', 'larry',
  'justin', 'scott', 'brandon', 'benjamin', 'samuel', 'gregory', 'alexander',
  'frank', 'patrick', 'raymond', 'jack', 'dennis', 'jerry', 'tyler', 'aaron',
  'jose', 'adam', 'nathan', 'henry', 'douglas', 'zachary', 'peter', 'kyle',
  'noah', 'ethan', 'jeremy', 'walter', 'christian', 'keith', 'roger', 'terry',
  'austin', 'sean', 'gerald', 'carlos', 'harold', 'dylan', 'arthur', 'lawrence',
  'jordan-lee', 'jesse', 'bryan', 'billy', 'bruce', 'gabriel', 'joe', 'logan',
  'alan', 'juan', 'albert', 'willie', 'elijah', 'wayne', 'randy', 'vincent',
  'mason', 'roy', 'ralph', 'bobby', 'russell', 'bradley', 'philip', 'phillip',
  'eugene', 'louis', 'harry', 'howard', 'fred', 'frederick', 'carl', 'glenn',
  'glen', 'stanley', 'leonard', 'ernest', 'martin', 'craig', 'todd', 'curtis',
  'norman', 'earl', 'allen', 'marvin', 'leroy', 'clarence', 'theodore', 'ted',
  'clifford', 'milton', 'herbert', 'herman', 'bernard', 'gordon', 'vernon',
  'leon', 'lloyd', 'gilbert', 'gene', 'floyd', 'cecil', 'chester', 'claude',
  'darrell', 'daryl', 'dale', 'dean', 'dwight', 'duane', 'dwayne', 'wade',
  'warren', 'wesley', 'don', 'dan', 'danny', 'dave', 'davey', 'dick', 'doug',
  'ed', 'eddie', 'edwin', 'edgar', 'elmer', 'emmett', 'ervin', 'irvin',
  'irving', 'felix', 'francis', 'franklin', 'fredrick', 'garry', 'gerard',
  'grant', 'greg', 'gus', 'guy', 'hank', 'hans', 'harvey', 'hector', 'hugh',
  'hugo', 'ian', 'ira', 'isaac', 'ivan', 'jake', 'jay', 'jed', 'jeff', 'jim',
  'jimmy', 'jimmie', 'jon', 'johnny', 'johnnie', 'josh', 'karl', 'ken',
  'kenny', 'kent', 'kirk', 'kurt', 'kurtis', 'lance', 'lane', 'lenny', 'leo',
  'leroy-james', 'les', 'lester', 'levi', 'lewis', 'lonnie', 'lou', 'lucas',
  'luke', 'luis', 'lyle', 'manuel', 'marcus', 'mario', 'marshall', 'matt',
  'maurice', 'max', 'maxwell', 'melvin', 'merle', 'mike', 'mickey', 'miguel',
  'mitchell', 'mitch', 'monte', 'monty', 'morris', 'moses', 'murray', 'nate',
  'nathaniel', 'neal', 'neil', 'nelson', 'nick', 'nicky', 'norbert', 'oliver',
  'omar', 'orville', 'oscar', 'otis', 'owen', 'pablo', 'pat-rick', 'pedro',
  'percy', 'pete', 'preston', 'quentin', 'quinn-cy', 'ramon', 'randall',
  'randolph', 'raul', 'ray', 'reed', 'reggie', 'reginald', 'rex', 'ricardo',
  'rich', 'rick', 'ricky', 'rickey', 'rob', 'robbie', 'roberto', 'rod',
  'rodney', 'roland', 'rolando', 'roman', 'ron', 'ronnie', 'roosevelt',
  'ross', 'ruben', 'rudy', 'rudolph', 'rufus', 'russ', 'rusty', 'salvador',
  'salvatore', 'sam', 'sammy', 'santiago', 'saul', 'sebastian', 'sergio',
  'seth', 'shane', 'shaun', 'shawn', 'sheldon', 'sherman', 'sidney', 'simon',
  'solomon', 'spencer', 'stan', 'stewart', 'stuart', 'sylvester', 'tanner',
  'taylor-james', 'terrance', 'terrence', 'thaddeus', 'tim', 'tom', 'tommy',
  'tony', 'travis', 'trent', 'trenton', 'trevor', 'troy', 'tyrone', 'ulysses',
  'vance', 'vaughn', 'vern', 'vic', 'victor', 'virgil', 'wallace', 'wally',
  'walt', 'ward', 'wendell', 'wilbert', 'wilbur', 'wilfred', 'will', 'willard',
  'willis', 'wilson', 'winston', 'woodrow', 'wyatt', 'xavier', 'zach',
  'zachariah', 'zeke', 'abe', 'abel', 'abraham', 'adrian', 'al', 'alberto',
  'alec', 'alejandro', 'alfonso', 'alfred', 'alfredo', 'allan', 'alonzo',
  'alton', 'alvin', 'amos', 'andre', 'andres', 'andy', 'angelo', 'antonio',
  'archie', 'arnold', 'arturo', 'aubrey-james', 'august', 'barney', 'barry',
  'bart', 'ben', 'bennett', 'bennie', 'benny', 'bernie', 'bert', 'bill',
  'blaine', 'blake', 'bo', 'bob', 'boyd', 'brad', 'braden', 'brady', 'brandt',
  'brendan', 'brennan', 'brent', 'brett', 'brock', 'broderick', 'bryant',
  'bryce', 'bud', 'buddy', 'burt', 'burton', 'byron', 'cale', 'caleb',
  'calvin', 'cameron-james', 'carlton', 'carson', 'cary', 'casper', 'cedric',
  'cesar', 'chad', 'chance', 'chandler', 'charlie', 'chase', 'chris', 'chuck',
  'clark', 'clay', 'clayton', 'clement', 'cliff', 'clifton', 'clint',
  'clinton', 'clyde', 'cody', 'colby', 'cole', 'coleman', 'colin', 'collin',
  'colt', 'colton', 'conner', 'connor', 'conrad', 'cooper', 'corey', 'cory',
  'cornelius', 'cristian', 'cruz', 'cyrus', 'dallas', 'dalton', 'damian',
  'damien', 'damon', 'dante', 'darian', 'darin', 'dario', 'darius', 'darnell',
  'darren', 'darrin', 'darryl', 'darwin', 'davis', 'dawson', 'deacon',
  'declan', 'demetrius', 'denny', 'denver', 'derek', 'derrick', 'desmond',
  'devin', 'devon-lee', 'dexter', 'diego', 'dillon', 'dirk', 'dominic',
  'dominick', 'donnie', 'donovan', 'dorian', 'drake', 'drew', 'duke',
  'duncan', 'dustin', 'dusty', 'earnest', 'easton', 'eddy', 'edmund',
  'eduardo', 'efrain', 'eli', 'elias', 'elliot', 'elliott', 'ellis', 'elmo',
  'elton', 'elvin', 'elvis', 'emanuel', 'emerson', 'emil', 'emilio',
  'emmanuel', 'enrique', 'erick', 'erik', 'ernesto', 'ernie', 'errol',
  'esteban', 'evan', 'everett', 'ezekiel', 'ezra', 'fabian', 'fernando',
  'fidel', 'finn', 'fletcher', 'forrest', 'foster', 'francisco', 'frankie',
  'franklyn', 'freddie', 'freddy', 'gabe', 'gael', 'garland', 'garrett',
  'garth', 'gavin', 'gerardo', 'gideon', 'gil', 'gilberto', 'gino',
  'giovanni', 'graham', 'grady', 'graysen', 'grayson', 'griffin', 'grover',
  'guillermo', 'gunnar', 'gunner', 'gustavo', 'harlan', 'harley-dave',
  'harrison', 'heath', 'helmut', 'herschel', 'hollis', 'homer', 'horace',
  'houston', 'hubert', 'hudson', 'humberto', 'hunter', 'ignacio', 'iker',
  'irwin', 'isaiah', 'isiah', 'ismael', 'israel', 'jackson', 'jaime-luis',
  'jared', 'jarrett', 'jarrod', 'jarvis', 'jasper', 'javier', 'jaxon',
  'jaxson', 'jayden-lee', 'jeffery', 'jeremiah', 'jermaine', 'jerome',
  'jerold', 'jess', 'joaquin', 'joel', 'joey', 'jonah', 'jonas', 'jorge',
  'jose-luis', 'josiah', 'juan-carlos', 'judson', 'julian', 'julio', 'julius',
  'kade', 'kaden', 'kai-den', 'kane', 'kareem', 'kasey-james', 'kayden',
  'keaton', 'keegan', 'keenan', 'kelvin', 'kendall-james', 'kendrick',
  'kennedy-james', 'kenton', 'kermit', 'kerry-lee', 'kieran', 'killian',
  'king', 'knox', 'kody', 'kolton', 'kris-topher', 'kristopher', 'lamar',
  'lamont', 'landon', 'lawson', 'leif', 'leland', 'lemuel', 'lennox',
  'leonardo', 'leopold', 'leroy-john', 'liam', 'lincoln', 'lindell', 'lionel',
  'lorenzo', 'lowell', 'lucian', 'luciano', 'luther', 'lyman', 'lyndon',
  'mack', 'malachi', 'malcolm', 'malik', 'manny', 'marc', 'marcel', 'marco',
  'marcos', 'marlon', 'marty', 'mateo', 'mathew', 'matthias', 'maverick',
  'maximilian', 'maximus', 'maynard', 'mckinley-james', 'micah', 'micheal',
  'miles', 'milo', 'misael', 'mohamed', 'moises', 'monroe', 'montgomery',
  'mordecai', 'morgan-lee', 'morton', 'moshe', 'myles', 'myron', 'nash',
  'nasir', 'ned', 'nestor', 'newton', 'nico', 'nigel', 'niko', 'nikolas',
  'nolan', 'norris', 'octavio', 'odell', 'olin', 'orlando', 'orin', 'orson',
  'osvaldo', 'oswaldo', 'otto', 'pascal', 'patricio', 'paxton', 'payton-james',
  'perry', 'phil', 'pierce', 'pierre', 'porter', 'prince', 'quincy', 'quintin',
  'quinton', 'rafael', 'raleigh', 'ramiro', 'rashad', 'raymundo', 'reece',
  'reese-james', 'remington', 'rene-luis', 'reuben', 'rhett', 'rigoberto',
  'riley-james', 'roberto-carlos', 'rocco', 'rocky', 'roderick', 'rodolfo',
  'rodrigo', 'rogelio', 'rolf', 'rollie', 'romeo', 'ronaldo', 'roscoe',
  'rowan-lee', 'royal', 'royce', 'ryder', 'ryker', 'rylan', 'salomon',
  'santino', 'santos', 'sawyer', 'scotty', 'seamus', 'sergei', 'shawn-michael',
  'shelby-james', 'silas', 'smith', 'sonny', 'stefan', 'sterling', 'steve',
  'stevie', 'sullivan', 'tate', 'tatum-james', 'teddy', 'terence', 'thad',
  'theo', 'tobias', 'toby', 'tod', 'tomas', 'tracey-lee', 'tristan', 'tucker',
  'turner', 'ty', 'tyrell', 'tyson', 'uriel', 'valentin', 'vincenzo', 'wilmer',
  'winfred', 'zander', 'zane', 'zion',
]);

/**
 * Guess gender from a first name (or full name - only the first token is
 * used). Returns 'unknown' for empty input, initials, and names not in the
 * lists (which includes deliberately omitted unisex names).
 */
export function guessGender(name: string | null | undefined): InferredGender {
  if (!name) return 'unknown';
  const first = name
    .trim()
    .split(/\s+/)[0]
    .toLowerCase()
    .replace(/[^a-z]/g, '');
  if (first.length < 2) return 'unknown';
  if (FEMALE.has(first) && MALE.has(first)) return 'unknown';
  if (FEMALE.has(first)) return 'female';
  if (MALE.has(first)) return 'male';
  return 'unknown';
}
